// ==UserScript==
// @name        duolingo
// @version     0.1
// @author      cubxx
// @match       *://*.duolingo.com/*
// @updateURL   https://cdn.jsdelivr.net/gh/cubxx/tampermonkey-script/src/duolingo.user.js
// @downloadURL https://cdn.jsdelivr.net/gh/cubxx/tampermonkey-script/src/duolingo.user.js
// @icon        https://d35aaqx5ub95lt.cloudfront.net/favicon.ico
// @grant       none
// ==/UserScript==

(async function () {
  if (self !== top) return;

  const { $, log, _ } = tm;

  // auto select story
  /** @type {{ stories: { id: string; title: string }[] }} */
  const { stories } = await (
    await fetch(
      'https://stories.duolingo.com/api2/practiceHubStories?' +
        new URLSearchParams({
          featuredStoryId: 'en-zh-history2-radio-play-0-autogenerated',
          fromLanguage: 'zh',
          learningLanguage: 'en',
        }),
      {
        headers: {
          Authorization: `Bearer ${(await cookieStore.get('jwt_token'))?.value}`,
        },
      },
    )
  ).json();

  $(document.body).observe(
    (ob) => {
      const el = $('a[data-test=practice-hub-nav]');
      if (!el) return;
      el.on('mouseenter', () => {
        const story = stories[Math.floor(Math.random() * stories.length)];
        el.set({
          title: story.title,
          href: `/stories/${story.id}?mode=read`,
          target: '_blank',
        });
      }).on('click', (e) => e.stopImmediatePropagation());
      ob.disconnect();
    },
    { subtree: true, childList: true },
  );
})();
